apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
spec:
  generators:
    - list:
        elements:
          - name: traefik
            namespace: ingress
            chart: traefik
            chartVersion: "34.4.0" 
            chartRepo: https://helm.traefik.io/traefik
            wave: "0"  
          - name: keycloak
            namespace: identity
            chart: bitnami/keycloak
            chartVersion: "24.4.10"  
            chartRepo: https://charts.bitnami.com
            wave: "0" 
          - name: argocd
            namespace: argocd
            chart: argo-cd
            chartVersion: "7.8.4"
            chartRepo: https://argoproj.github.io/argo-helm
            # NOTE: ArgoCD has configuration for SSO from Keycloak and ingress from Traefik, so run after.
            wave: "1"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      sources:
        - repoURL: '{{chartRepo}}'
          targetRevision: '{{chartVersion}}'
          chart: '{{chart}}'
          helm:
            valueFiles:
              - $values/{{name}}/values.yaml
        - repoURL: https://github.com/wosiu/gitops-platform
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true 
          - ApplyOutOfSyncOnly=true

