apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-app
spec:
  generators:
    - list:
        elements:
          #- name: traefik
          #  namespace: ingress
          #  chart: traefik
          #  chartVersion: "34.4.0" 
          #  chartRepo: https://helm.traefik.io/traefik
          #  wave: "0"  
          #- name: keycloak
          #  namespace: identity
          #  chart: keycloak
          #  chartVersion: "24.4.10"  
          #  chartRepo: https://charts.bitnami.com/bitnami
          #  wave: "1" 
          - name: argocd
            namespace: argocd
            chart: argo-cd
            chartVersion: "7.8.4"
            chartRepo: https://argoproj.github.io/argo-helm
            wave: "2"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      sources:
        - repoURL: '{{chartRepo}}'
          targetRevision: '{{chartVersion}}'
          chart: '{{chart}}'
          helm:
            valueFiles:
              - $values/values.yaml
        - repoURL: https://github.com/wosiu/gitops-platform
          targetRevision: main
          path: '{{name}}'
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true 
